name: Example
description: Example Action

inputs:
  token:
    description: actions token
    required: true
  event:
    description: handle event
    required: true

runs:
  using: node16
  main: dist/index.js
