name: Example
description: Example Action

inputs:
  token:
    description: actions token
    required: false
    default: ${{ github.token }}
  event:
    description: handle event
    required: false
    default: ${{ toJSON(github.event) }}

runs:
  using: node16
  main: dist/index.js
