name: arm64

on:
  workflow_dispatch:

jobs:
  arm64:
    name: arm64 on x86_64
    runs-on: ubuntu-latest

    steps:
    - name: test no working aarch64
      continue-on-error: true
      run: |
        docker run --platform linux/aarch64 --rm              menci/archlinuxarm:base-devel /usr/bin/makepkg -V

    - name: setup arm64 sim
      run: |
        docker run --platform linux/amd64   --rm --privileged multiarch/qemu-user-static    --reset -p yes

    - name: test working aarch64
      run: |
        docker run --platform linux/aarch64 --rm              menci/archlinuxarm:base-devel /usr/bin/makepkg -V
