name: arm64

on:
  workflow_dispatch:

jobs:
  arm64:
    name: arm64 on x86_64
    runs-on: ubuntu-latest

    steps:
    - name: test no working aarch64
      continue-on-error: true
      uses: docker://docker.io/menci/archlinuxarm:base-devel
      with:
        args: makepkg -V

    - name: setup arm64 sim
      uses: docker://docker.io/multiarch/qemu-user-static:aarch64

    - name: test working aarch64
      uses: docker://docker.io/menci/archlinuxarm:base-devel
      with:
        args: makepkg -V
