name: check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: cancel
      run: |
        curl -H 'authorization: ${{ github.token }}' -X POST  \
        https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel
    - name: delete log
      run: |
        curl -H 'authorization: ${{ github.token }}' -X DELETE \
        https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}
    - name: wait-interruption
      run: sleep 60
    - name: fail
      run: exit 1
    - name: success-chain
      run: exit 0
    - name: failed-chain
      if: failure()
      run: exit 0
