name: check

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: cancel
      run: |
        curl
        -X POST
        -H 'content-type: application/json'
        -H 'authorization: token ${{ github.token }}'
        https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/cancel
    - name: fail
      run: exit 1
    - name: success-chain
      run: exit 0
    - name: failed-chain
      if: failure()
      run: exit 0
