{
  "name": "echo objects",
  "on": {
    "issue_comment": {
      "type": ["created", "edited", "deleted"]
    }
  },
  "jobs": {
    "echo": {
      "runs-on": "ubuntu-latest",
      "steps": [
        { "name": "just do it.", "run": "echo '${{ toJSON(github.event) }}'" },
        { "name": "...do it.",   "run": "curl -v ${{ github.event.issue.pull_request.url }}" }
      ]
    }
  }
}
