name: use local actions

on:
  issue_comment:
    type:
    - created
    - edited

jobs:
  let:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: another_4
      - name: let
        uses: ./actions/example
